function T_fin = transion(q1,q2,q3,q4,q5,q6)
%TRANSION
%    T_FIN = TRANSION(Q1,Q2,Q3,Q4,Q5,Q6)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    30-Dec-2021 17:24:46

t2 = cos(q1);
t3 = cos(q2);
t4 = cos(q3);
t5 = cos(q4);
t6 = cos(q5);
t7 = cos(q6);
t8 = sin(q1);
t9 = sin(q2);
t10 = sin(q3);
t11 = sin(q4);
t12 = sin(q5);
t13 = sin(q6);
t14 = q2+q3+q4;
t15 = cos(t14);
t16 = t2.*t12;
t17 = sin(t14);
t18 = t8.*t12;
t19 = t6.*(3.9e+1./4.0e+2);
t20 = t5.*(5.7e+1./5.0e+2);
t21 = t11.*(5.7e+1./5.0e+2);
t25 = t5.*t12.*(3.9e+1./4.0e+2);
t26 = t11.*t12.*(3.9e+1./4.0e+2);
t22 = t2.*t6.*t15;
t23 = t6.*t8.*t15;
t24 = -t21;
t29 = t19+1.065e-1;
t31 = t20+t26;
t27 = -t23;
t28 = t18+t22;
t32 = t4.*t31;
t33 = t10.*t31;
t35 = t24+t25+2.37e+2./1.0e+3;
t30 = t16+t27;
t34 = -t33;
t36 = t4.*t35;
t37 = t10.*t35;
t38 = t32+t37;
t41 = t34+t36+3.3e+1./1.25e+2;
t39 = t9.*t38;
t42 = t3.*t41;
t40 = -t39;
T_fin = reshape([t7.*t28-t2.*t13.*t17,-t7.*t30-t8.*t13.*t17,t13.*t15+t6.*t7.*t17,0.0,-t13.*t28-t2.*t7.*t17,t13.*t30-t7.*t8.*t17,t7.*t15-t6.*t13.*t17,0.0,t6.*t8-t15.*t16,-t2.*t6-t15.*t18,-t12.*t17,0.0,t8.*t29+t2.*(t39-t42),-t2.*t29+t8.*(t39-t42),-t3.*t38-t9.*t41+1.8e+1./1.25e+2,1.0],[4,4]);
